name: pr

on:
  - pull_request

jobs:
  format-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@v2.0.1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run -s format:imports:check

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@v2.0.1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run -s format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@v2.0.1
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run -s lint:check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -s build
      - run: pnpm run -s test
